### ISSUE TITLE
How to import to Andriod-Studio?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [carlemil/JuliaLiveWallpaper#1]
I keep failing doing such a basic thing...

**Comment by AndroidDeveloperLB** [comment]
In fact, it doesn't even get imported well to Ecilpse.
It can't find "ScriptC_julia" , even after compiling.

**Comment by carlemil** [comment]
ScriptC_julia is the result of the renderscipt being compiled and is used to "link" the java code with the script. So if that is missing you haven't setup eclipse properly for using with renderscript. Try following some guide and get a simple example to work first :)
And as far as andropidstudio goes i don't think the support for renderscript is good yet, havent tried it out for some time for renderscript but use it at work for app development on a every day basis.

**Comment by AndroidDeveloperLB** [comment]
I had some issues with it, and asked here:
http://stackoverflow.com/q/31872140/878126
It was probably because I used too-new versions of some components. 

The Renderscript should be in the "rs" folder, btw.
