### ISSUE TITLE
Why have SurfaceView if it's not used?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [carlemil/JuliaLiveWallpaper#2]

**Comment by carlemil** [comment]
Where do you see a SurfaceView? (Haven't touched this project for about a year, and cant remember having one it it).

**Comment by AndroidDeveloperLB** [comment]
It's in the layout. Now that I think about it, you probably used the same layout for both the activity and the live wallpaper itself, so for the activity you used an imageView, while for the live wallpaper you probably used surfaceView.

**Comment by carlemil** [comment]
Still cant see it :) Got a link to the file on github that contains it?

On Thu, Oct 1, 2015 at 9:37 AM, AndroidDeveloperLB <notifications@github.com

**Comment by AndroidDeveloperLB** [comment]
How odd. It was probably changed since the last time I've cloned this project. Sorry. closing this issue.

**Comment by carlemil** [comment]
Must have been a while since you cloned it, haven't touched it in about a
year :D Did you do any similar things with RS that are available on
github/google play? Always fun to see what others comes up with!

**Comment by AndroidDeveloperLB** [comment]
Nothing yet. I'm only learning how to use Renderscript.

**Comment by carlemil** [comment]
Ok, don't mix it up with live wallpapers to start with then, just paint on
a canvas in a view, easier to get thing working that way i think. Once that
is working it can easily be moved to a wallpaper or other thing.

**Comment by AndroidDeveloperLB** [comment]
Yes, thank you. If you wish, you can try out my own repos:
https://github.com/AndroidDeveloperLB?tab=repositories
or my tiny app I've made on my spare time:
https://play.google.com/store/apps/details?id=com.lb.app_manager
